# JWT配置
app:
  jwt:
    secret: ${JWT_SECRET:APZvEuDRA9S2j2m9bpBKPPEiCbSRChKayBYEDc4RIK8=}
    expiration: 86400000 # 24小时
    header: Authorization
    prefix: Bearer

# 安全配置
spring:
  security:
    user:
      name: admin123
      password: admin123
      roles: ADMIN
    basic:
      enabled: false

# 管理后台配置
litemall:
  admin:
    # 管理员相关配置
    avatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif
