# JWT配置
app:
  jwt:
    secret: ${WX_JWT_SECRET:APZvEuDRA9S2j2m9bpBKPPEiCbSRChKayBYEDc4RIK8=}
    expiration: 7200000 # 2小时
    issuer: LITEMALL
    subject: this is litemall token
    audience: MINIAPP

# 微信小程序配置
litemall:
  wx:
    app-id: wxa5b486c6b918ecfb
    app-secret: e04004829d4c383b4db7769d88dfbca1
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify
    # 商户证书文件路径
    key-path: xxxxx
    # 消息推送配置token
    token:
    # 消息推送配置AesKey
    aes-key: